### ISSUE TITLE
Can not see gpu information in LxdMosaic

### ISSUE THREAD

**Issue by YangTakeshi** [turtle0x1/LxdMosaic#450]
**Describe the bug**
Can not see gpu information in LxdMosaic, like this:
![图片](https://user-images.githubusercontent.com/8491763/142979988-7ecf49f8-4fdf-4b0d-8f2f-05eb82a2e2f1.png)
But in LxdMosaic container，i can use nvidia-smi to see all gpus, like this:
![图片](https://user-images.githubusercontent.com/8491763/142980108-108b80ae-eecc-4af6-aa71-0e8574dee24e.png)

**Server Information:**
![图片](https://user-images.githubusercontent.com/8491763/142980256-8ef43bf0-3e6a-498a-954a-fe544bdaeb75.png)

**Comment by turtle0x1** [comment]
Can you see your GPU's in `lxc query /1.0/resources`? Is this master branch or the current release?

**Comment by YangTakeshi** [comment]
> 

i cant see gpu in `lxc query /1.0/resources`, my version is current release

**Comment by turtle0x1** [comment]
Ah, you will need a newer version of LXD to see your GPU's on the screen unfortunately. What version are you running V3 stable?

**Comment by YangTakeshi** [comment]
> 

yes
![图片](https://user-images.githubusercontent.com/8491763/143155827-f96f9281-5da1-4e30-bf78-c1c6e6be4658.png)

**Comment by turtle0x1** [comment]
Unfortunately you'll need a later version of LXD to see your GPU's in LXDMosaic. 

You should consider upgrading as V3 is security fixes now only.

LXDMosaic still supports V3 (to the point we added "fake projects" internally, to keep backwards compat) but we will eventually drop support for it (probably June 2023, when LXD team drops support for it).

**Comment by YangTakeshi** [comment]
> Unfortunately you'll need a later version of LXD to see your GPU's in LXDMosaic.
> 
> You should consider upgrading as V3 is security fixes now only.
> 
> LXDMosaic still supports V3 (to the point we added "fake projects" internally, to keep backwards compat) but we will eventually drop support for it (probably June 2023, when LXD team drops support for it).

i updated lxd to 4.0 and now i can see gpu by `lxc query /1.0/resource`, but in web page, i cannot see my nvidia gpu(RTX3090) name, like this:
![图片](https://user-images.githubusercontent.com/8491763/143383543-f6c0c36f-f3f9-464e-9434-04e72f1c1cc6.png)
![图片](https://user-images.githubusercontent.com/8491763/143383570-5a02d576-6143-468b-8ed0-598c9a486982.png)

**Comment by turtle0x1** [comment]
Okay cool with that info I should be able to debug this, thanks :smile:

**Comment by turtle0x1** [comment]
Fixed in 35943f765ae5a9d2f8e94bd456480b37ab794bbf

Comes with a new layout for the page also;


![server_overview](https://user-images.githubusercontent.com/12494629/144520567-500d0b28-151f-450d-9d9a-d7808632ae19.png)

**Comment by YangTakeshi** [comment]
> Fixed in [35943f7](https://github.com/turtle0x1/LxdMosaic/commit/35943f765ae5a9d2f8e94bd456480b37ab794bbf)
> 
> Comes with a new layout for the page also;
> 
> ![server_overview](https://user-images.githubusercontent.com/12494629/144520567-500d0b28-151f-450d-9d9a-d7808632ae19.png)

Thanks for your work

**Comment by YangTakeshi** [comment]
> Fixed in [35943f7](https://github.com/turtle0x1/LxdMosaic/commit/35943f765ae5a9d2f8e94bd456480b37ab794bbf)
> 
> Comes with a new layout for the page also;
> 
> ![server_overview](https://user-images.githubusercontent.com/12494629/144520567-500d0b28-151f-450d-9d9a-d7808632ae19.png)

![图片](https://user-images.githubusercontent.com/8491763/144535000-91f4c1eb-b196-49c0-aeed-7e117110f37e.png)
I still can't see my GPUs T_T

**Comment by turtle0x1** [comment]
On the server page can you open the developer tools (ctrl + shift + i) and see if there any errors? It looks like its erroring.

Ill take a look into the create container modal

**Comment by YangTakeshi** [comment]
> On the server page can you open the developer tools (ctrl + shift + i) and see if there any errors? It looks like its erroring.
> 
> Ill take a look into the create container modal

![图片](https://user-images.githubusercontent.com/8491763/144599847-9a3165d8-2339-47ad-b721-fb1c2eba7123.png)
It shows that. In fact, the browser already gets the json of the gpu information through the api. When I debugged through the browser, I found that the program did not determine if a GPU other than NVIDIA was present, and my server had a non-NVIDIA graphics card present, thus causing the program to break abnormally and not continue executing subsequent code.
![图片](https://user-images.githubusercontent.com/8491763/144600429-bfd2fe00-c362-49fe-9466-de83fc119244.png)
![图片](https://user-images.githubusercontent.com/8491763/144601276-cc35c51b-fa40-43a6-8120-395939c9eb72.png)
